package tablename

import (
	"strings"

	"github.com/skyrocketOoO/gorm-enhance-plugin/utils"

	"gorm.io/gorm"
)

func GetTableNames(db *gorm.DB) (tableNames []string, err error) {
	return db.Migrator().GetTables()
}

func GenTableNamesCode(db *gorm.DB, path string) error {
	tableNames, err := GetTableNames(db)
	if err != nil {
		return err
	}
	code := "// Code generated by gorm-enhance-plugin. DO NOT EDIT.\n\n"
	code += "package tb\n\n"
	code += "const (\n"
	for _, tableName := range tableNames {
		code += "\t" + strings.ToUpper(
			string(tableName[0]),
		) + tableName[1:] + " = \"" + tableName + "\"\n"
	}
	code += ")\n"

	return utils.CreateOrReplaceFile(path, code)
}
